spring.application.name=pqrs

####################################################
# MONGODB
####################################################

# DOCKER
#spring.data.mongodb.uri=mongodb://mongodb:27017/pqrs_db

# LOCAL
 spring.data.mongodb.uri=mongodb://localhost:27017/pqrs_db

####################################################
# SERVER
####################################################

server.port=8080
server.address=0.0.0.0

####################################################
# MULTIPART
####################################################

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

####################################################
# LOGS
####################################################

logging.level.org.springframework.data.mongodb=INFO
logging.level.org.springframework.security=INFO